version: "2"
services:
  front-end:
    build:
      context: ./front-end
    depends_on:
      - express-server
    ports:
      - "3000:3000"
    env_file:
     - ./front-end/src/.env

  express-server:
    build:
      context: ./express-server
    ports:
      - "5000:5000"

   # Jaeger
  jaeger-all-in-one:
    hostname: jaeger-all-in-one
    image: jaegertracing/all-in-one:1.49
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_HTTP_CORS_ALLOWED_ORIGINS=*
      - COLLECTOR_OTLP_HTTP_CORS_ALLOWED_HEADERS=*
    ports:
      - "16685"
      - "4318:4318"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
