receivers:
  otlp:
    protocols:
      http:
        cors:
          allowed_origins: ["*"]
          allowed_headers: ["*"]
exporters:
  logging:
    verbosity: Detailed
processors:
  batch:
service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging]
      processors: [batch]
